### ISSUE TITLE
F1 -score error during fm-co evaluation

### ISSUE THREAD

**Issue by bontorhumala** [bontorhumala/untar#49]
comparing original_df and generic_model_df throws 'array must be same length' error. Need to downgrade Pandas https://github.com/nilmtk/nilmtk/issues/493

However, downgrading cause ImportError: libgfortran.so.1: cannot open shared object file: No such file or directory when importing nilmtk.

Will manually update nilmtk according to: https://github.com/nilmtk/nilmtk/pull/544/files since the related PR failed

**Comment by bontorhumala** [comment]
manual update will cause strange behavior in fraction_energy_assigned_correctly (returns NaN). The F1 score itself always 0.0.

maybe this is why the PR is not merged. Will just implement own F1 score based on NILMTK code then.

**Comment by daragh27** [comment]
@bontorhumala  Thanks very much.
