### ISSUE TITLE
New paper on disaggregation

### ISSUE THREAD

**Issue by bontorhumala** [bontorhumala/untar#50]
https://nipunbatra.github.io/papers/batra_aaai2017.pdf

**Comment by bontorhumala** [comment]
> It must be clarified that both our approach and Gemello can produce an energy breakdown only at a monthly temporal resolution, unlike NILM solutions that can produce a high frequency appliance energy time-series. However, previous studies have shown sustained savings even at a monthly resolution (Kelly and Knottenbelt 2016)

**Comment by bontorhumala** [comment]
Paper on effectiveness: https://arxiv.org/pdf/1605.00962.pdf

**Comment by akshay-sn** [comment]
Compared to Gemello, our approahc can track individual appliance at a fine
grained level i.e. every minute/day correct?

**Comment by bontorhumala** [comment]
Yes, we designed this for real time disaggregation. I read this [paper](https://arxiv.org/pdf/1605.00962.pdf) by Kelly and Knottenbelt (developed Neural NILM and NILMTK developer). Their paper:

> Does disaggregated electricity feedback reduce domestic electricity consumption? A systematic review of the literature

They came to a conclusion

> Disaggregation has many use-cases beyond feedback. This paper specifically considers a single use-case of disaggregation: Reducing energy consumption via feedback. Averaged across the population, there is evidence that disaggregated feedback may help to reduce electricity consumption by ~0.7-4.5%. But disaggregation might not be necessary to achieve this saving because aggregate feedback may be equally effective. Amongst ‘energy enthusiasts’, disaggregated feedback might save more energy but fine-grained disaggregation may not be necessary.

This is interesting for me because it contradicts current hype where lot of companies and startups are working on disaggregation. Btw I got the result for generic model disaggregation (Filtered Means-CO). I adapt the output so that we can use NILMTK's metrics directly. 

Does not look good (e.g. FTE around 50-60%). Over the weekend I will plot them and see if it can be improved. Also look into FHMM etc to work with the generic models
