### ISSUE TITLE
Improvement on FHMM using motifs/sample

### ISSUE THREAD

**Issue by bontorhumala** [bontorhumala/untar#74]
Checkout https://github.com/beckel/nilm-eval

Get inspiration from variation of FHMM:
- Kolter approximate inference FHMM
- Look for new features for FHMM i.e mix HMM model with mathematical model (Parson work)
- NILM-eval paper by Beckel

**Comment by bontorhumala** [comment]
Test https://github.com/mattjj/pyhsmm-factorial as it may be based on Kolter's paper (https://github.com/nilmtk/nilmtk/issues/67)

**Comment by bontorhumala** [comment]
it is possible to build HMM models based on sample only (not full trace) as demonstrated by Approximate Inference HMM (Kolter, 2012). Implemented in https://github.com/bontorhumala/untar/pull/76

**Comment by bontorhumala** [comment]
Looks promising: 
![image](https://user-images.githubusercontent.com/943854/30365623-9748be7c-9868-11e7-814d-d961898661ec.png)
![image](https://user-images.githubusercontent.com/943854/30365627-9bdb28c6-9868-11e7-87a1-c8bec66fef29.png)
![image](https://user-images.githubusercontent.com/943854/30365630-9f3eed5e-9868-11e7-9b09-344b6e7e4f9f.png)
![image](https://user-images.githubusercontent.com/943854/30365635-a2cd7846-9868-11e7-86cd-741ac3e2a353.png)
![image](https://user-images.githubusercontent.com/943854/30365641-a6ee739e-9868-11e7-9105-1e1186fe3aee.png)

**Comment by bontorhumala** [comment]
Sometimes, several appliances do not have sample at all. Current method tends to be too strict somehow

**Comment by bontorhumala** [comment]
Problem with DBSCAN in generating agg_one_at_time_features is that it removes outliers, including important ones (no corresponding agg_one_at_time_features for dish washer in the middle).
![screenshot from 2017-09-13 14-30-01](https://user-images.githubusercontent.com/943854/30378466-953d71a6-9893-11e7-84e8-f4e6c0b031c9.png)

**Comment by bontorhumala** [comment]
Previously use test_elec (different date than predicted_priors_elec). When I use same date range (agg_elec), samples are too similar across appliances.

Problem in __find_similar: somehow large mean (washing machine) is not recognized, same classification for microwave and dish washer,
![image](https://user-images.githubusercontent.com/943854/30388559-5cba62e0-98b0-11e7-9cc6-02891d88aafd.png)
![image](https://user-images.githubusercontent.com/943854/30388669-a521f2aa-98b0-11e7-8970-85223f1f647e.png)

**Comment by bontorhumala** [comment]
Previous fix does is not stable. Instead of using classifier, use simple weighted least distance method in __find_similar as implemented in https://github.com/bontorhumala/untar/pull/78. Results are more consistent among REDD house 1 and 2. However. problem of dish washer in house 2 still persists

![image](https://user-images.githubusercontent.com/943854/30401019-20e3c8fa-98d9-11e7-97c4-fbfc8881d836.png)

pp_common_features show 1200-ish trace. However possible_appliance_feature does not have similar mean (ony 800-ish with 400 variance)

**Comment by bontorhumala** [comment]
After removing agg_features with high variance ( > 0.4*means ), we obtain less features and therefore DBSCAN can focus on clustering means.

Result on REDD 2

![image](https://user-images.githubusercontent.com/943854/30423479-3b1c8152-9943-11e7-86ed-a0a0ec9d5004.png)
![image](https://user-images.githubusercontent.com/943854/30423491-452b59d4-9943-11e7-8fed-36ab540ea399.png)
![image](https://user-images.githubusercontent.com/943854/30423503-51e99186-9943-11e7-9027-a5ddd1261e8f.png)
![image](https://user-images.githubusercontent.com/943854/30423522-61ea412a-9943-11e7-9adf-fd665164f1fb.png)
![image](https://user-images.githubusercontent.com/943854/30423530-6c8f8252-9943-11e7-8e66-a7ae4d30c4f4.png)

**Comment by bontorhumala** [comment]
Also good results with house 1:

![image](https://user-images.githubusercontent.com/943854/30424342-f705f22a-9945-11e7-8b88-e9e362dd1ce3.png)
![image](https://user-images.githubusercontent.com/943854/30424368-06ff2fac-9946-11e7-9a71-b09695793ad6.png)
![image](https://user-images.githubusercontent.com/943854/30424389-170b66a4-9946-11e7-856f-02c395b2558a.png)
![image](https://user-images.githubusercontent.com/943854/30424407-298716f2-9946-11e7-8eca-350678daae7f.png)
![image](https://user-images.githubusercontent.com/943854/30424418-38d0e246-9946-11e7-8753-cde4f3d32bb5.png)

**Comment by bontorhumala** [comment]
Problems with UK-DALE house 1:

1. Badly tuned_models causing bad predicted_priors and thus bad pp_common_features. Fixed by using backup from folder *models/4 - tuned model final*
2. *agg_features* have so many feature with mean values around 90-100W. This causes DBSCAN to ignore other, rarely occuring features such as those with mean values 1500-2000 (grouped together). Fixed by using _MeanShift_ for _agg_features_

Both fixes are in https://github.com/bontorhumala/untar/pull/80

Results for UK-DALE house 1:

Results for UK-DALE house 2:

**Comment by bontorhumala** [comment]
DRED is also good
![image](https://user-images.githubusercontent.com/943854/30441215-0c5447de-9979-11e7-96ed-1eddbf629c42.png)
![image](https://user-images.githubusercontent.com/943854/30441228-14ac4d1e-9979-11e7-9da9-386912ab9bb0.png)
![image](https://user-images.githubusercontent.com/943854/30441234-1f5b5a34-9979-11e7-9e9a-e0736ae6bd36.png)
![image](https://user-images.githubusercontent.com/943854/30441251-2835070e-9979-11e7-8334-443d511a87b1.png)

**Comment by akshay-sn** [comment]
So does this mean the results are much better??

**Comment by bontorhumala** [comment]
We dont know yet, but this is promising because we can build an accurate HMM model for each appliance from these samples. I still need to implement the FHMM disaggregator. possibly based on http://nbviewer.jupyter.org/github/nilmtk/nilmtk/blob/v0.1.0/notebooks/fhmm.ipynb

**Comment by bontorhumala** [comment]
https://github.com/bontorhumala/untar/pull/82
