### ISSUE TITLE
Getting more results

### ISSUE THREAD

**Issue by bontorhumala** [bontorhumala/untar#88]
## Within dataset

Train using UKDALE house 4 and 5
Test using UKDALE house 1 and 2

|         | fridge | toaster | washing machine | dishwasher | kettle | microwave | AVG |
|---------|--------|---------|-----------------|------------|--------|-----------|------|
| House 1 | 0.83   | 0.13    | 0.26            | 0          |        |           | 0.31 |
| House 2 | 0.53   |         | 0.21            | 0.26       | 0.6    | 0.29      | 0.38 |

Train using UKDALE house 1 and 2
Test using UKDALE house 4 and 5

|         | fridge | toaster | washing machine | dishwasher | kettle | television | AVG |
|---------|--------|---------|-----------------|------------|--------|------------|-----|
| House 4 | 0.74   |         | 0.15            |            | 0.38   |            | 0.42 |
| House 5 | 0.87   |         | 0.57            | 0.65       | 0.83   | 0.16       | 0.62 |

**Comment by bontorhumala** [comment]
Cross dataset

Train REDD 1 2  UK DALE 2 5, test DRED 1

|         | fridge | microwave | washing machine |
|---------|--------|---------|-----------------|
| House 1 | 0.82   | 0.2    | 0.15       |

**Comment by akshay-sn** [comment]
I did not understand the result.

Akshay

**Comment by bontorhumala** [comment]
I updated the description. Do you understand it now?

**Comment by akshay-sn** [comment]
yes understood.

**Comment by bontorhumala** [comment]
see https://github.com/bontorhumala/untar/pull/90
