### ISSUE TITLE
Adding things for paper

### ISSUE THREAD

**Issue by bontorhumala** [bontorhumala/untar#89]
- [x] Add figure 1: appliance data --> general model. smart meter data --> tuned model --> disaggregate
- [x] Fill in XXX citations
- [x] Fill in XXX about fridge example

**Comment by bontorhumala** [comment]
in dropbox

**Comment by akshay-sn** [comment]
Did you fix the XXX?

**Comment by akshay-sn** [comment]
I have changed the tex again, please ask me before you change XXX
